const SURFACE = "#fbfaf7";
const PANEL = "#ffffff";
const INK = "#171412";
const MUTED = "rgba(23,20,18,.58)";
const LINE = "rgba(23,20,18,.10)";
const GOLD = "#b9822f";

export const css = {
  app:{
    minHeight:"100vh",
    background:"#efede7",
    color:INK,
    fontFamily:"'DM Mono', ui-monospace, SFMono-Regular, Menlo, monospace",
    overflow:"hidden"
  },
  shell:{
    display:"grid",
    gridTemplateColumns:"320px minmax(0, 1fr)",
    height:"100vh",
    gap:0
  },
  sidebar:{
    position:"relative",
    zIndex:60,
    display:"flex",
    flexDirection:"column",
    gap:18,
    padding:"22px 18px",
    background:SURFACE,
    borderRight:`1px solid ${LINE}`,
    boxShadow:"8px 0 28px rgba(23,20,18,.05)",
    overflowY:"auto"
  },
  sidebarMobile:{
    border:`1px solid ${LINE}`,
    borderRadius:8,
    boxShadow:"0 14px 40px rgba(23,20,18,.16)"
  },
  sidebarHeader:{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:12},
  brandBlock:{minWidth:0},
  brand:{fontFamily:"Georgia,serif",fontSize:30,fontWeight:700,color:INK,lineHeight:1},
  brandSub:{fontFamily:"'DM Mono',monospace",fontSize:11,color:GOLD,letterSpacing:".08em",marginLeft:6},
  brandLine:{fontSize:11,lineHeight:1.5,color:MUTED,marginTop:8,maxWidth:230},
  compactButton:{
    height:30,
    padding:"0 10px",
    borderRadius:7,
    border:`1px solid ${LINE}`,
    background:"#f2efe8",
    color:INK,
    cursor:"pointer",
    fontFamily:"inherit",
    fontSize:11
  },
  sidebarSection:{display:"flex",flexDirection:"column",gap:9},
  sectionTitle:{
    fontSize:10,
    letterSpacing:".14em",
    textTransform:"uppercase",
    color:"rgba(23,20,18,.42)",
    fontWeight:600
  },
  epochGrid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7},
  epochButton:(ep)=>({
    display:"flex",
    alignItems:"center",
    gap:7,
    minHeight:34,
    padding:"7px 9px",
    borderRadius:7,
    border:`1px solid ${ep.stripe}33`,
    background:ep.pillBg,
    color:ep.pillText,
    cursor:"pointer",
    fontFamily:"inherit",
    fontSize:11,
    textAlign:"left"
  }),
  epochDot:(color)=>({width:7,height:7,borderRadius:"50%",background:color,flexShrink:0}),
  periodGrid:{display:"flex",flexWrap:"wrap",gap:6},
  periodPill:(per)=>({
    flexShrink:0,
    padding:"5px 8px",
    borderRadius:7,
    fontSize:10.5,
    letterSpacing:0,
    fontWeight:600,
    cursor:"pointer",
    border:`1px solid ${per.color}88`,
    background:per.color+"26",
    color:"#26211c",
    whiteSpace:"nowrap",
    fontFamily:"inherit"
  }),
  sidebarFooter:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:"auto",paddingTop:8},
  sidebarAction:{
    height:36,
    borderRadius:7,
    border:`1px solid ${LINE}`,
    background:PANEL,
    color:INK,
    cursor:"pointer",
    fontFamily:"inherit",
    fontSize:12,
    boxShadow:"0 1px 0 rgba(23,20,18,.04)"
  },

  main:{display:"flex",flexDirection:"column",minWidth:0,padding:18,gap:14,background:"#efede7"},
  mainHeader:{
    display:"flex",
    alignItems:"center",
    justifyContent:"space-between",
    gap:18,
    flexShrink:0
  },
  eyebrow:{fontSize:11,letterSpacing:".16em",textTransform:"uppercase",color:"rgba(23,20,18,.45)",marginBottom:5},
  pageTitle:{fontFamily:"Georgia,serif",fontSize:"clamp(30px, 4vw, 54px)",lineHeight:1.02,fontWeight:600,margin:0,color:INK,letterSpacing:0,maxWidth:760},
  pageSubtitle:{fontSize:14,lineHeight:1.55,color:MUTED,margin:"10px 0 0",maxWidth:620},
  headerActions:{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"},
  primaryAction:{
    height:36,
    padding:"0 14px",
    borderRadius:7,
    border:"1px solid rgba(185,130,47,.42)",
    background:"#fff7e8",
    color:"#7a4b12",
    cursor:"pointer",
    fontFamily:"inherit",
    fontSize:12,
    fontWeight:600
  },
  secondaryAction:{
    height:36,
    padding:"0 12px",
    borderRadius:7,
    border:`1px solid ${LINE}`,
    background:PANEL,
    color:INK,
    cursor:"pointer",
    fontFamily:"inherit",
    fontSize:12
  },
  timelineCard:{
    position:"relative",
    display:"flex",
    flexDirection:"column",
    minHeight:0,
    flex:1,
    overflow:"hidden",
    borderRadius:8,
    border:`1px solid ${LINE}`,
    background:PANEL,
    boxShadow:"0 16px 50px rgba(23,20,18,.08)"
  },
  timelineToolbar:{
    height:54,
    display:"flex",
    alignItems:"center",
    justifyContent:"space-between",
    gap:16,
    padding:"0 16px",
    borderBottom:`1px solid ${LINE}`,
    background:"#fffdf8",
    flexShrink:0
  },
  timelineMeta:{display:"flex",alignItems:"baseline",gap:9,minWidth:0},
  metaLabel:{fontSize:10,letterSpacing:".14em",textTransform:"uppercase",color:"rgba(23,20,18,.4)"},
  metaValue:{fontSize:13,color:INK},
  toolbarHint:{fontSize:11,color:MUTED,lineHeight:1.45},

  exploreGrid:{
    display:"grid",
    gridTemplateColumns:"repeat(6, minmax(132px, 1fr))",
    gap:10,
    flexShrink:0
  },
  exploreCard:(card)=>({
    minHeight:118,
    display:"flex",
    flexDirection:"column",
    alignItems:"flex-start",
    justifyContent:"space-between",
    gap:12,
    padding:14,
    borderRadius:18,
    border:`1px solid ${card.color}26`,
    background:`linear-gradient(180deg, ${card.bg}, #ffffff)`,
    boxShadow:"0 10px 24px rgba(23,20,18,.06)",
    cursor:"pointer",
    fontFamily:"inherit",
    textAlign:"left",
    transition:"transform .16s ease, box-shadow .16s ease"
  }),
  exploreIcon:(color)=>({
    width:34,
    height:34,
    borderRadius:14,
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    background:color,
    color:"#fff",
    fontFamily:"Georgia,serif",
    fontSize:20,
    fontWeight:700,
    boxShadow:`0 8px 18px ${color}40`
  }),
  exploreContent:{display:"flex",flexDirection:"column",gap:3,minWidth:0},
  exploreKicker:{fontSize:10,letterSpacing:".12em",textTransform:"uppercase",color:"rgba(23,20,18,.46)",fontWeight:600},
  exploreTitle:{fontFamily:"Georgia,serif",fontSize:21,lineHeight:1.08,color:INK},
  exploreText:{fontSize:11,lineHeight:1.45,color:MUTED},

  wrap:{flex:1,position:"relative",overflow:"hidden",cursor:"grab",minHeight:360,background:"#faf7f2"},
  cnv:{position:"absolute",top:0,left:0,width:"100%",height:"100%"},
  zoomBtns:{position:"absolute",right:14,top:14,display:"flex",gap:6,zIndex:20},
  zoomBtn:{
    width:36,
    height:36,
    borderRadius:7,
    background:PANEL,
    border:`1px solid ${LINE}`,
    cursor:"pointer",
    display:"flex",
    alignItems:"center",
    justifyContent:"center",
    fontSize:18,
    fontWeight:500,
    color:INK,
    boxShadow:"0 4px 14px rgba(23,20,18,.10)"
  },
  mini:{position:"absolute",bottom:14,right:14,width:176,height:34,background:"#eee8dc",border:`1px solid ${LINE}`,borderRadius:5,overflow:"hidden",zIndex:20},
  statusbar:{height:36,display:"flex",alignItems:"center",gap:14,flexShrink:0,color:MUTED},
  statusEpoch:{fontFamily:"Georgia,serif",fontSize:13,fontStyle:"italic",color:INK,flex:1,minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"},
  aiBadge:(v)=>({display:"flex",alignItems:"center",gap:6,padding:"4px 9px",borderRadius:999,background:"#fff7e8",border:"1px solid rgba(185,130,47,.24)",fontSize:10,letterSpacing:".06em",opacity:v?1:0,transition:"opacity .3s"}),
  aiDot:{width:6,height:6,borderRadius:"50%",background:GOLD,animation:"dp 1.2s ease-in-out infinite"},
  statusR:{fontSize:11,color:MUTED},

  searchWrap:{position:"relative",flexShrink:0},
  searchInput:{
    height:42,
    width:"100%",
    borderRadius:8,
    border:`1px solid ${LINE}`,
    background:PANEL,
    padding:"0 38px 0 34px",
    fontSize:13,
    fontFamily:"inherit",
    color:INK,
    outline:"none",
    boxShadow:"0 1px 0 rgba(23,20,18,.04)"
  },
  searchIcon:{position:"absolute",left:12,top:"50%",transform:"translateY(-50%)",fontSize:13,color:"rgba(23,20,18,.38)",pointerEvents:"none"},
  searchClear:{position:"absolute",right:11,top:"50%",transform:"translateY(-50%)",fontSize:12,color:"rgba(23,20,18,.45)",cursor:"pointer",background:"none",border:"none",padding:0,lineHeight:1},
  searchDropdown:{position:"absolute",top:"calc(100% + 8px)",left:0,right:0,background:PANEL,border:`1px solid ${LINE}`,borderRadius:8,boxShadow:"0 18px 42px rgba(23,20,18,.18)",zIndex:100,overflow:"hidden"},
  searchHeader:{padding:"9px 12px 7px",borderBottom:`1px solid ${LINE}`,display:"flex",alignItems:"center",gap:6},
  searchHeaderTxt:{fontSize:10,color:"rgba(23,20,18,.45)",letterSpacing:".08em",textTransform:"uppercase",flex:1},
  searchSpinner:{width:11,height:11,borderRadius:"50%",border:"1.5px solid rgba(23,20,18,.15)",borderTop:`1.5px solid ${GOLD}`,animation:"spin .7s linear infinite"},
  searchItem:{display:"flex",alignItems:"flex-start",gap:10,padding:"11px 12px",cursor:"pointer",borderBottom:`1px solid ${LINE}`,transition:"background .12s"},
  searchDot:(c)=>({width:8,height:8,borderRadius:"50%",background:c,flexShrink:0,marginTop:5}),
  searchItemInfo:{flex:1,minWidth:0},
  searchItemTitle:{display:"block",fontSize:15,fontWeight:500,color:INK,marginBottom:3,fontFamily:"Georgia,serif"},
  searchItemDate:{display:"block",fontSize:11,color:GOLD,marginBottom:3},
  searchItemDesc:{fontSize:12,color:MUTED,lineHeight:1.55,overflow:"hidden",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical"},
  searchItemRel:{display:"block",fontSize:10,color:"rgba(23,20,18,.44)",fontStyle:"italic",marginTop:3},
  searchItemNav:{fontSize:12,color:"rgba(23,20,18,.32)",flexShrink:0,marginTop:3},
  searchEmpty:{padding:"20px 12px",textAlign:"center",fontSize:12,color:MUTED},
  searchError:{padding:"10px 12px",fontSize:12,lineHeight:1.45,color:"#9f2f24",background:"rgba(180,40,30,.08)",borderBottom:"1px solid rgba(180,40,30,.12)"},
  searchAiBadge:{display:"inline-flex",alignItems:"center",gap:4,padding:"2px 7px",borderRadius:999,background:"rgba(185,130,47,.12)",border:"1px solid rgba(185,130,47,.22)",fontSize:10,color:GOLD,letterSpacing:".05em"},

  tt:(t)=>({position:"absolute",left:t.x,top:t.y,pointerEvents:"none",zIndex:50,background:"#171412",color:SURFACE,borderRadius:8,padding:"9px 12px",maxWidth:230,boxShadow:"0 10px 28px rgba(0,0,0,.28)"}),
  ttDate:{fontSize:9,color:"#e6b76b",letterSpacing:".08em",marginBottom:4},
  ttTitle:{fontFamily:"Georgia,serif",fontSize:15,lineHeight:1.3},
  ttHint:{fontSize:9,color:"rgba(251,250,247,.48)",marginTop:5},

  legend:(o)=>({position:"absolute",left:0,top:0,bottom:0,width:"min(280px, 88vw)",background:PANEL,borderRight:`1px solid ${LINE}`,transform:o?"translateX(0)":"translateX(-100%)",transition:"transform .3s cubic-bezier(.16,1,.3,1)",overflowY:"auto",padding:18,zIndex:35,boxShadow:"8px 0 26px rgba(23,20,18,.10)"}),
  legHead:{fontSize:10,letterSpacing:".14em",textTransform:"uppercase",color:"rgba(23,20,18,.42)",fontWeight:600,marginBottom:9},
  legItem:{display:"flex",alignItems:"center",gap:8,marginBottom:8},
  legDot:(c)=>({width:9,height:9,borderRadius:"50%",background:c,flexShrink:0}),
  legBar:(c)=>({width:14,height:6,borderRadius:2,background:c,flexShrink:0}),
  legLbl:{fontSize:12,color:INK},

  panel:(o)=>({position:"absolute",right:0,top:0,bottom:0,width:"min(520px, 94vw)",background:PANEL,borderLeft:`1px solid ${LINE}`,transform:o?"translateX(0)":"translateX(100%)",transition:"transform .34s cubic-bezier(.16,1,.3,1)",display:"flex",flexDirection:"column",zIndex:40,boxShadow:"-16px 0 42px rgba(23,20,18,.14)"}),
  panelStripe:(c)=>({height:5,flexShrink:0,background:c}),
  panelHdr:{padding:"24px 28px 18px",borderBottom:`1px solid ${LINE}`,flexShrink:0,position:"relative"},
  panelClose:{position:"absolute",top:14,right:16,width:30,height:30,borderRadius:"50%",background:"#f3f0ea",border:`1px solid ${LINE}`,cursor:"pointer",fontSize:12,display:"flex",alignItems:"center",justifyContent:"center",color:INK},
  panelCat:{fontSize:10,letterSpacing:".16em",textTransform:"uppercase",fontWeight:600,marginBottom:5,opacity:.76},
  panelDate:{fontSize:13,color:GOLD,marginBottom:9},
  panelTitle:{fontFamily:"Georgia,serif",fontSize:31,lineHeight:1.15,color:INK,paddingRight:32},
  panelBody:{flex:1,overflowY:"auto",padding:"24px 30px",scrollbarWidth:"thin",scrollbarColor:"#d8d0c3 transparent"},
  panelContent:{fontFamily:"Georgia,serif",fontSize:18,lineHeight:1.78,color:INK},
  panelError:{padding:"11px 28px",fontSize:12,lineHeight:1.5,color:"#9f2f24",background:"rgba(180,40,30,.08)",borderBottom:"1px solid rgba(180,40,30,.12)"},
  loading:{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:180,gap:12},
  bars:{display:"flex",gap:4,alignItems:"flex-end",height:22},
  barsLbl:{fontSize:10,letterSpacing:".12em",color:"rgba(23,20,18,.45)",textTransform:"uppercase"},
  bmBar:{display:"flex",alignItems:"center",gap:8,padding:"11px 28px 9px",borderBottom:`1px solid ${LINE}`,flexShrink:0,flexWrap:"wrap"},
  bmBtn:(active,col)=>({display:"inline-flex",alignItems:"center",gap:4,padding:"5px 10px",borderRadius:999,fontSize:11,letterSpacing:".03em",fontWeight:600,cursor:"pointer",border:`1px solid ${col||"rgba(23,20,18,.2)"}`,background:active?`${col||GOLD}18`:"transparent",color:active?(col||GOLD):MUTED,transition:"all .15s",whiteSpace:"nowrap",fontFamily:"inherit"}),
  bmViewPanel:{position:"absolute",left:0,top:0,bottom:0,width:"min(360px, 92vw)",background:PANEL,borderRight:`1px solid ${LINE}`,transform:"translateX(0)",display:"flex",flexDirection:"column",zIndex:38,boxShadow:"12px 0 34px rgba(23,20,18,.12)"},
  bmViewItem:{display:"flex",alignItems:"flex-start",gap:9,padding:"11px 14px",borderBottom:`1px solid ${LINE}`,cursor:"pointer",transition:"background .12s"},
  bmTag:(col)=>({display:"inline-flex",alignItems:"center",padding:"2px 7px",borderRadius:999,fontSize:10,letterSpacing:".04em",border:`1px solid ${col}44`,background:`${col}12`,color:col,flexShrink:0,marginTop:1}),
  inlineIconButton:{cursor:"pointer",color:"rgba(23,20,18,.38)",fontSize:12,lineHeight:1,background:"transparent",border:0,padding:0},
  inlineConfirmButton:{cursor:"pointer",fontSize:12,color:"#0a7848",background:"transparent",border:0,padding:"2px 3px"},
  addTagButton:{padding:"4px 9px",borderRadius:999,border:`1px dashed ${LINE}`,fontSize:11,color:MUTED,cursor:"pointer",background:"transparent",fontFamily:"inherit"}
};
